apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garagehq-meta-pvc
  namespace: garagehq
  labels:
    app: garagehq
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual-garage
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garagehq-data-pvc
  namespace: garagehq
  labels:
    app: garagehq
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual-garage
  resources:
    requests:
      storage: 20Gi
