apiVersion: v1
kind: Secret
metadata:
  name: garagehq-secrets
  namespace: garagehq
  labels:
    app: garagehq
type: Opaque
stringData:
  rpc_secret: "${GARAGE_RPC_SECRET}"
  admin_token: "${GARAGE_ADMIN_TOKEN}"
  metrics_token: "${GARAGE_METRICS_TOKEN}"
